#! /bin/bash

# $1 is the parent directory from which we start the search 
# $2 is the max depth of the search from parent directory
# $3 Commit message
# Inputs can be missordered if proper tags are provided:
				# -f or --folder for parent directory
				# -d or --depth for depth
				# -m or --message for message

# Default Values				
DEPTH=1
FOLDER="./"
MSG="Automated update [Might not work]"

# Formatting options
BLACK="\033[30m"
RED="\033[31m"
GREEN="\033[32m"
YELLOW="\033[33m"
BLUE="\033[34m"
PINK="\033[35m"
CYAN="\033[36m"
WHITE="\033[37m"
NC="\033[0;39m"
BOLD="\e[1m"
BLKBKG="\e[40m"
UNDRLN="\e[4m"
#echo $DEPTH


# Catch simple input
if (( "$#" )); then
	MSG=$3
	DEPTH=$2
	FOLDER=$1
fi


# Read options
while (( "$#" )); do
	case $1 in
		-f|--folder)
			shift
			FOLDER=$1
			#echo "Folder Option: $FOLDER"
			;;
		-m|--message)
			# Catch message for commits -can be ommitted-
			echo "Message for the commit --Remember it will apply to all git repos--"
			read MSG
			;;
		-d|--depth)
			shift
			echo $1
			DEPTH=$1
			#echo "Depth Option: $DEPTH"
			;;
		*)
			#echo "no input"
			;;
	esac
	shift
done

#echo $DEPTH


		
# Search and show
find ${FOLDER} -maxdepth ${DEPTH} -name ".git" -execdir printf "\n${BOLD}${BLKBKG}${UNDRLN}${YELLOW}Directory:${NC}  " \; -execdir pwd \; -execdir git commit -am "$MSG" \; -execdir git push \; -execdir printf "\n" \;
