#! /bin/bash

isOpen=false
test "$(pidof spotify | wc -w)" == 0 && (spotify;isOpen=true; exit 1)

if [ "$isOpen" == false ]; then 
	wmctrl -a spotify
fi
#$isSpotyRunning="$(pidof spotify | wc -w)"
#if [$(pidof spotify | wc -w) -eq 0]
#then
	#spotify
#fi

